title: Email Dev Updates
author: Colin Whelan
email: clnwhelan@gmail.com
github_username:  Colin-Whelan
description: > # this means to ignore newlines until "show_exerpts:"
  A blog for keeping track of and showing off updates in the email development landscape. 
  Tools I develop and tips I learn will be shared here.
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5

# tag_permalink_style: pretty
# tag_page_layout: tag_page
# tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: colin-whelan

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://github.com/Colin-Whelan
      icon: github-square
      color: cyan

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: github
  #github_username: bitbrain
  #avatar_source: local
  #avatar_path: /assets/avatar.png

# Build settings
# theme: jekyll-dash
remote-theme: LU-SIFE/jekyll-dash-theme

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
